---
#
# Payment Microservice Deployment
#
apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-host
  labels:
    app: payment-host
    tier: backend
spec:
  selector:
    matchLabels:
      app: payment-host
      tier: backend
  replicas: 1
  template:
    metadata:
      labels:
        app: payment-host
        tier: backend
    spec:
      containers:
        - name: payment-host
          image: $$REGISTRY_SERVERpayment-host:$$IMAGE_VERSION
          imagePullPolicy: IfNotPresent
          env:
          - name: ASPNETCORE_ENVIRONMENT
            value: "$$ENVIRONMENT_NAME"
          - name: ASPNETCORE_ORCHESTRATOR
            value: "k8s"